
project_id = "vnhwhyufevcixgelsujb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions.send-slack-notification]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = true

[functions.create-notification]
verify_jwt = true

[functions.send-invitation-email]
verify_jwt = true
